# Generated by Django 5.2.1 on 2025-06-23 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dbteacher1',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_email', models.EmailField(max_length=254, unique=True)),
                ('t_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepics/admins/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dbstudent1',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepics/')),
                ('s_firstname', models.CharField(max_length=50)),
                ('s_lastname', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.BigIntegerField()),
                ('s_guardianphonenumber', models.BigIntegerField()),
                ('s_qualification', models.TextField()),
                ('s_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('s_password', models.CharField(blank=True, max_length=128)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
