# Generated by Django 5.2.1 on 2025-07-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstudent1',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.badge'),
        ),
    ]
